INSERT INTO Devices (device_type, location, status, uptime_percentage, last_checked) VALUES
('Router', 'HQ - Server Room', 'Online', 99.85, GETDATE()),
('Switch', 'HQ - Network Closet', 'Online', 98.75, GETDATE()),
('Firewall', 'HQ - Server Room', 'Online', 99.60, GETDATE()),
('Laptop', 'Finance Office', 'In Use', 95.20, GETDATE()),
('Desktop', 'HR Office', 'In Use', 97.10, GETDATE()),
('Printer', 'Lobby', 'Online', 92.50, GETDATE()),
('Server', 'Data Center', 'Online', 99.95, GETDATE()),
('Access Point', 'Warehouse', 'Online', 97.80, GETDATE()),
('Camera', 'Security Wing', 'Online', 96.40, GETDATE()),
('POS Terminal', 'Cafeteria', 'In Use', 93.85, GETDATE()),
('Router', 'Branch A', 'Offline', 85.60, GETDATE()),
('Switch', 'Branch A', 'Online', 97.50, GETDATE()),
('Firewall', 'Branch B', 'Online', 98.40, GETDATE()),
('Laptop', 'Executive Office', 'In Use', 94.30, GETDATE()),
('Desktop', 'IT Office', 'In Use', 98.85, GETDATE()),
('Printer', 'Operations', 'Online', 91.70, GETDATE()),
('Server', 'Branch B', 'Online', 99.20, GETDATE()),
('Access Point', 'HQ - Hallway', 'Online', 97.10, GETDATE()),
('Camera', 'Parking Lot', 'Online', 95.30, GETDATE()),
('POS Terminal', 'Retail Store', 'In Use', 92.10, GETDATE());
